config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
		resources :users
		root to: "users#index"
	end

	#root to: 'visitors#index'

	devise_for :users
	resources :users
	resources :vendors
	resources :test_sequence
	resources :message_log
	resources :vendor_test_sequence
	resources :vendor_test_seq_step
	resources :message_log
	resources :request_log

	get 'vendor_request_message/:id/sendRequest' => 'vendor_request_message#sendRequest', as: 'sendRequest_vendor_request_message'
	get 'vendor_request_message/results' => 'vendor_request_message#results'
	resources :vendor_request_message


	get 'test_seq_step/packages' => 'test_seq_step#packages'
	resources :test_seq_step   #, :except => ['new']
	get 'test_seq_step/new/:id' => 'test_seq_step#new', as: 'new_test_seq_step2'

	get "home/index" => 'home'

	root to: 'home#splash'
end

app/controllers/test_seq_step_controller.rb
class TestSeqStepController < ApplicationController

	layout "test_seq_step"

	def index
	end
	def edit
		@step = TestSeqStep.find(params[:id])
		@pkg = Package.all
	end

	def new
		@test_sequence_id = params[:id]
	end

	def packages
		a = my_packages.map{|s| {
			text: s.name,
			nodes: s.package_group.map{ |p| {
				text: p.name,
				nodes: p.messages.map{ |m| {text: m.name, id: m.message_id}}
			}}
		}}

		render json: a.to_json
	end

	def destroy
		@step = TestSeqStep.find(params[:id])
		@step.destroy

		redirect_to edit_test_sequence_path(:id => @step.test_sequence_id)
	end



	def show
		#@step = TestSeqStep.find(params[:id])
		#@pkg = my_packages
		redirect_to edit_test_sequence_path(:id => @step.test_sequence_id)
	end

	def create
		@step = TestSeqStep.new(step_params)
		@step.next_step_id = nil


		if @step.save
			redirect_to edit_test_sequence_path(:id => @step.test_sequence_id)
		else
			render index
		end
	end

	def update
		@step = TestSeqStep.find(params[:id])

		if @step.update_attributes(step_params)
			flash[:success] = "Test Sequence Step updated"
			redirect_to edit_test_sequence_path(:id => @step.test_sequence_id)
		else
			rendor :edit
		end
	end


	private

	def my_packages
		return Package.joins(:vendors).where(vendor_id = same_vendor)
	end

	def same_vendor
		current_user.vendor_id
	end

	def step_params
		params.require(:test_seq_step).permit(:in_message_id, :esb_url, :harness_url, :swap_corrid_flag, :test_sequence_id, :next_step_id)
	end

end

app/helpers/test_seq_step_helper.rb
module TestSeqStepHelper

	private
	def same_vendor
		current_user.vendor_id
	end


end

app/views/test_seq_step/_sidebar.html.erb
<h2>Messages</h2>
<div id="message_tree" class="foo"></div>

app/views/test_seq_step/edit.html.erb
<h1>Edit Test Sequence Step</h1>
<%= form_for @step do |f| %>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :message %>
    </div>
    <div class="field-unit__field test_seq_step_field-unit__field">
      <input id="msg_read_only" name="msg_ro", type="text" value=<%= Message.find(@step.in_message_id).name %> disabled>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :esb_url %>
    </div>
    <div class="field-unit__field test_seq_step_field-unit__field">
      <%= f.text_field :esb_url %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :harness_url %>
    </div>
    <div class="field-unit__field test_seq_step_field-unit__field">
      <%= f.text_field :harness_url %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :next_step_id%>
    </div>
    <div class="field-unit__field test_seq_step_field-unit__field">
      <%= f.select :next_step_id, TestSeqStep.where(test_sequence_id: @step.test_sequence_id).collect {|x| [ x.id, x.id]} %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_seq_step/new.html.erb
<h1>New Test Sequence Step</h1>

<%= form_for :test_seq_step, url: test_seq_step_index_path do |f| %>

<%= f.hidden_field :test_sequence_id, value: @test_sequence_id %>

<div class="field-unit field-unit--string">
	<div class="field-unit__label">
 		<%= f.label :message%>
 	</div>
 	<div class="field-unit__field">
      <%= f.select :in_message_id, Message.all.collect {|x| [ x.name, x.id]}, {}%>
    </div>
</div>

<div class="field-unit field-unit--string">
	<div class="field-unit__label">
    	<%= f.label :esb_url%>
    </div>
 	<div class="field-unit__field">
    <%= f.text_field :esb_url%>
  </div>
</div>

<div class="field-unit field-unit--string">
	<div class="field-unit__label">
    	<%= f.label :harness_url%>
    </div>
 	<div class="field-unit__field">
    <%= f.text_field :harness_url%>
  </div>
</div>

<div class="field-unit field-unit--string">
  <div class="field-unit__label">
      <%= f.label "Swap Correlation ID" %><br>
  </div>
  <div class="field-unit__field">
    <%= f.select(:swap_corrid_flag) do %>
        <% [['Yes', 1], ['No', 0]].each do |c| -%>
          <%= content_tag(:option, c.first, value: c.last) %>
        <% end %>
    <% end %>
  </div>
</div>

<div class="field-unit field-unit--string">
	<div class="field-unit__label">
 		<%#= f.label :next_step_id, :class => "field-unit__label" %>
 	</div>
 	<div class="field-unit__field">
      <%#= f.select :next_step_id, TestSeqStep.where(test_sequence_id: @step.test_sequence_id).collect {|x| [ x.id, x.id]}, {}, :class => "field-unit__field"%>
    </div>
</div>
  
<div class="form-actions">
    <%= f.submit %>
</div>
<% end %>

app/views/test_seq_step/show.html.erb
<div class="collection-data">
  <table>
    <tr>
      <td><strong>ID:</strong></td>
      <td><%= @ts.test_sequence_id%></td>
    </tr>
    <tr>
      <td><strong>Name:</strong></td>
      <td><%= @ts.name %></td>
    </tr>
    <tr>
      <td><strong>Description:</strong></td>
      <td><%= @ts.description %></td>
    </tr>

    </table>

    <%= render "show_collection",  ts: @ts %>


</div>