config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
		resources :users
		root to: "users#index"
	end

	#root to: 'visitors#index'

	devise_for :users
	resources :users
	resources :vendors
	resources :test_sequence
	resources :message_log
	resources :vendor_test_sequence
	resources :vendor_test_seq_step
	resources :message_log
	resources :request_log

	get 'vendor_request_message/:id/sendRequest' => 'vendor_request_message#sendRequest', as: 'sendRequest_vendor_request_message'
	get 'vendor_request_message/results' => 'vendor_request_message#results'
	resources :vendor_request_message


	get 'test_seq_step/packages' => 'test_seq_step#packages'
	resources :test_seq_step   #, :except => ['new']
	get 'test_seq_step/new/:id' => 'test_seq_step#new', as: 'new_test_seq_step2'

	get "home/index" => 'home'

	root to: 'home#splash'
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	self.table_name = 'vendor'
	self.primary_key = :vendor_id
	has_and_belongs_to_many :packages, join_table: "vendor_packages", :foreign_key => :vendor_id
	has_many :users, :class_name => 'User'

	validates :name, presence: true,
	length: { minimum: 4 }
end

app/controllers/vendors_controller.rb
# Vendor CRUD, forms located under
# app/views/vendors dir
class VendorsController < ApplicationController
	before_action :authenticate_user!
	before_action :super_only

	# user app/views/vendors
	layout "vendors"

	def index
		@vendors = Vendor.all
	end

	def show
		@vendor = Vendor.find(params[:id])
	end


	def edit
		@vendor = Vendor.find(params[:id])
	end

	# todo : modify to allow for package links at create time
	def create
		@vendor = Vendor.new(vendor_params)

		if @vendor.save
			redirect_to @vendor
		else
			render 'new'
		end
	end

	def update
		@vendor = Vendor.find(params[:id])

		# kill all linked vendor_packages, and then recreate
		@vendor.packages.destroy_all
		@vendor.packages << Package.find(params[:vendor][:package_ids].reject { |c| c.empty? })

		if @vendor.update_attributes(vendor_params)
			flash[:success] = "Vendor updated"
			redirect_to vendors_path
		else
			rendor :edit
		end
	end

	def destroy
		@vendor = Vendor.find(params[:id])
		@vendor.destroy

		redirect_to vendors_path
	end



	private

	def vendor_params
		params.require(:vendor).permit(:name, :default_url)
	end

	def flashes

	end
end

app/helpers/vendors_helper.rb
module VendorsHelper



end

app/views/vendors/_collection.html.erb
<table class="collection-data" aria-labelledby="page-title">
 
 <table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Default URL</th>
    <th>Packages</th>
    <th>URL</th>
    <th></th>
    <th></th>
  </tr>

  <tbody>
    <% vendors.each do |vendor| %>
      <tr class="table__row"
          role="link"
          tabindex="0"
          >
        <td><%= vendor.id %></td>
        <td><%= vendor.name %></td>
         <td><%= vendor.default_url %></td>
        <td><%= vendor.packages.map { |p| p.name }.join(", ") %></td>
        <td><%= vendor.default_url %></td>

        <td><%= link_to(
          t("actions.edit"),
          [:edit, vendor],
          class: "action-edit",
        ) %></td>

        <td><%= link_to 'Destroy', vendor_path(vendor),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vendors/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash--<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/vendors/_sidebar.html.erb
<%#
# Sidebar

This partial is used to display the sidebar in Administrate.
By default, the sidebar contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<ul class="sidebar__list">
	<li>
	   <%= link_to("Home", home_index_path ) %>
    </li>
    <li>
      <%= link_to("Vendors", vendors_path)%>
    </li>
    <li>
      <%= link_to("Test Seqs", test_sequence_index_path) %>
    </li>
</ul>

app/views/vendors/edit.html.erb
<h1>Edit</h1>
<%= form_for @vendor do |f| %>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :name, :class => "field-unit__label" %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :name, :class => "field-unit__field" %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :default_url, :class => "field-unit__label" %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :default_url, :class => "field-unit__field" %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label "Packages", :class => "field-unit__label" %>
    </div>
    <div class="field-unit__field">
      <%= f.select :package_ids, Package.all.collect {|x| [ x.name, x.id]}, {} , :multiple => true, :class => "field-unit__field"%>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/index.html.erb
<h1>Vendors</h1>
 
<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <td><%= link_to 'New', new_vendor_path, method: :get, class: "button" %></td>
  </div>
</header>

<%= render "collection",  vendors: @vendors %>
 

app/views/vendors/new.html.erb
<h1>New Vendor</h1>
<%= form_for :vendor, url: vendors_path do |f| %>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :name, :class => "field-unit__label" %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :name, :class => "field-unit__field" %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :default_url, :class => "field-unit__label" %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :default_url, :class => "field-unit__field" %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label "Packages", :class => "field-unit__label" %>
    </div>
    <div class="field-unit__field">
      <%= f.select :package_ids, Package.all.collect {|x| [ x.name, x.id]}, {} , :multiple => true, :class => "field-unit__field"%>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/show.html.erb
<div class="collection-data">
	<table>
		<tr>
  		<td><strong>ID:</strong></td>
  		<td><%= @vendor.id%></td>
  	</tr>
  	<tr>
  		<td><strong>Name:</strong></td>
  		<td><%= @vendor.name %></td>
  	</tr>

  	<tr>
  		<td><strong>Packages:</strong></td>
  		<td><%= @vendor.packages.map { |p| p.name }.join(", ") %></td>
  	</tr>
  	</table>


</div>

 