config/routes.rb
Rails.application.routes.draw do
	namespace :admin do
		resources :users
		root to: "users#index"
	end

	#root to: 'visitors#index'

	devise_for :users
	resources :users
	resources :vendors
	resources :test_sequence
	resources :message_log
	resources :vendor_test_sequence
	resources :vendor_test_seq_step
	resources :message_log
	resources :request_log

	get 'vendor_request_message/:id/sendRequest' => 'vendor_request_message#sendRequest', as: 'sendRequest_vendor_request_message'
	get 'vendor_request_message/results' => 'vendor_request_message#results'
	resources :vendor_request_message


	get 'test_seq_step/packages' => 'test_seq_step#packages'
	resources :test_seq_step   #, :except => ['new']
	get 'test_seq_step/new/:id' => 'test_seq_step#new', as: 'new_test_seq_step2'

	get "home/index" => 'home'

	root to: 'home#splash'
end

app/models/vendor_request_message.rb
class VendorRequestMessage < ActiveRecord::Base
    self.table_name = 'vendor_request_message'
    self.primary_key = :vendor_request_message_id

    belongs_to :message, :class_name => 'Message', :foreign_key => :message_id
    belongs_to :vendor, :class_name => 'Vendor', :foreign_key => :vendor_id
end

app/controllers/vendor_request_message_controller.rb
class VendorRequestMessageController < ApplicationController

  layout "vendor_request_message"

  require "rexml/document"
  require 'ostruct'

  def index
    @messages = VendorRequestMessage.where(vendor_id: same_vendor)
  end

  def create
    @message = VendorRequestMessage.new(test_params)
    @message.vendor_id = same_vendor

    if @message.save
      sendMessage()
    else
      render index
    end
  end

  def destroy
    @msg = VendorRequestMessage.find(params[:id])
    @msg.destroy

    redirect_to vendor_request_message_index_path
  end

  def results
    @message = VendorRequestMessage.find(params[:id])
    render :results
  end

  def show
    @ts = VendorRequestMessage.find(params[:id])
    render :results
  end

  def update
    puts "======== update called"
    @message = VendorRequestMessage.find(params[:id])

    cmd = params[:commit]

    if cmd == "Send"
      sendMessage()
    else
      if @message.update_attributes(test_params)
        sendMessage()
      else
        render :edit
      end
    end
  end

  def edit
    @page_title = 'Edit Request Message'
    @message = VendorRequestMessage.find(params[:id])
  end

  def sendRequest
    @message = VendorRequestMessage.find(params[:id])
    sendMessage
  end



  private

  def sendMessage

    @response = OpenStruct.new
    @response.message = @message.message_txt

    uri = URI.parse @message.sent_to_url

    http = Net::HTTP.new(uri.host, uri.port)

    req = Net::HTTP::Post.new(uri.request_uri)
    req.body = @message.message_txt
    req.content_type = 'text/xml'

    reply = Net::HTTP.new(uri.host, uri.port).start { |http| http.request req}


    @response.code = reply.code
    @response.body = reply.body

    @page_title = 'Results'

    render :results
  rescue => e
    flash.now[:error] = "Request failed : " + e.message
    @response.code = "No Results"
    @response.body = "No Results"
    render :results
  end


  def same_vendor
    current_user.vendor_id
  end

  def test_params
    params.require(:vendor_request_message).permit(:message_id, :message_txt, :description, :sent_to_url)
  end

  def flashes

  end


end

app/helpers/vendor_request_message_helper.rb
module VendorRequestMessageHelper
end

app/views/vendor_request_message/_collection.html.erb
<table class="collection-data" aria-labelledby="page-title">
  <table>
    <tr>
      <th>ID</th>
      <th>Message</th>
      <th>Description</th>
      <th>URL</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <tbody>
      <% messages.each do |m| %>
        <tr class="table__row"
          role="link"
          tabindex="0"
          >
          <td><%= m.id %></td>
          <td><%= m.message.name %></td>
          <td><%= m.description %></td>
          <td><%= m.sent_to_url %></td>
          <td><%= link_to(
          t("edit"),
          [:edit, m],
          class: "action-edit",
        ) %></td>
          <td><%= link_to(
          t("send"),
          [:sendRequest, m],
                    class: "action-sendRequest",
        ) %></td>
          <td><%= link_to 'Destroy', vendor_request_message_path(m),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/vendor_request_message/edit.html.erb
<h1><%= @page_title %></h1>
<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <td><%= link_to 'Back', :back, class: "button" %></td>
  </div>
</header>
<%= form_for @message do |f| %>
  <%= f.hidden_field :message_id, value: @message.message_id %>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :description %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :description %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :sent_to_url %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :sent_to_url %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :message_txt %>
    </div>
    <div class="field-unit__field">
      <%= f.text_area :message_txt %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Save" %>
    <%= link_to 'Default', '#', :onclick => 'javascript:resetMessageText();', data: { confirm: 'Are you sure?' }, class: "button"%>
    <% if @page_title != 'Edit Request Message' %>
      <%= f.submit "Send"%>
    <% end %>
  </div>
<% end %>
<% Message.all.each do |m| %>
  <%= content_tag(:div, m.default_message_txt, id: "message_#{m.message_id}", class: "page_data") %>
<% end %>

app/views/vendor_request_message/index.html.erb
<h1>Request Message</h1>
<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <td><%= link_to 'New', new_vendor_request_message_path, method: :get, class: "button" %></td>
  </div>
</header>

<%= render "collection",  messages: @messages %>

app/views/vendor_request_message/new.html.erb
<h1>New Vendor Request Message</h1>
<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <td><%= link_to 'Back', :back, class: "button" %></td>
  </div>
</header>
<%= form_for :vendor_request_message, url: vendor_request_message_index_path do |f| %>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :message%>
    </div>
    <div class="field-unit__field">
      <%= f.select :message_id, Message.all.collect {|x| [ x.name, x.id]}, {},
      :onChange => "javascript:setMessageText($(this).val())"%>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :description %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :description %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :sent_to_url %>
    </div>
    <div class="field-unit__field">
      <%= f.text_field :sent_to_url %>
    </div>
  </div>
  <div class="field-unit field-unit--string">
    <div class="field-unit__label">
      <%= f.label :message_txt %>
    </div>
    <div class="field-unit__field">
      <%= f.text_area :message_txt %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit "Save" %>
    <%= link_to 'Default', '#', :onclick => 'javascript:resetMessageText();', class: "button"%>
    <%= f.submit "Send", formaction: vendor_request_message_index_path %>
  </div>
<% end %>
<% Message.all.each do |m| %>
  <%= content_tag(:div, m.default_message_txt, id: "message_#{m.message_id}", class: "page_data") %>
<% end %>

app/views/vendor_request_message/results.html.erb
<h1><%= @page_title %></h1>
<header class="header">
  <h1 class="header__heading" id="page-title"><%= content_for(:title) %></h1>
  <div class="header__actions">
    <td><%= link_to 'Back', :back, class: "button" %></td>
  </div>
</header>
<div class="field-unit field-unit--string">
  <div class="field-unit__label">
    <label for="response_code">Response Code : </label>
  </div>
  <div class="field-unit__field">
    <%= @response.code %>
  </div>
</div>
<div class="field-unit field-unit--string">
  <div class="field-unit__label">
    <label for="message">SOAP Message :</label>
  </div>
  <pre class="pre_message"><%= formatXML(@response.message) %></pre>
</div>
<div class="field-unit field-unit--string">
  <div class="field-unit__label">
    <label for="response_code">SOAP Response :</label>
  </div>
  <pre class="pre_message"><%= formatXML(@response.body) %></pre>
</div>